// Real Chrome side-panel regression. Extension pages opened as ordinary tabs
// cannot exercise native docking, viewport changes or activeTab grants.
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,cp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=process.env.PLAYWRIGHT_MODULE?require(process.env.PLAYWRIGHT_MODULE):await import('playwright');
const project=resolve(import.meta.dirname,'..'),artifacts=join(project,'artifacts','sidepanel');
const temporary=await mkdtemp(join(tmpdir(),'diffuse-sidepanel-e2e-')),extension=join(temporary,'extension');
await mkdir(artifacts,{recursive:true});await cp(join(project,'extension'),extension,{recursive:true});
const manifest=JSON.parse(await readFile(join(extension,'manifest.json'),'utf8'));
// Only the disposable fixture copy gets host access. Real toolbar actions must
// still grant tabCapture/captureVisibleTab for each captured tab.
manifest.host_permissions=['http://127.0.0.1/*'];
await writeFile(join(extension,'manifest.json'),JSON.stringify(manifest));
const workerPath=join(extension,'background.js');
await writeFile(workerPath,(await readFile(workerPath,'utf8')).replace("import * as reviews from './review-store.mjs';","import * as reviews from './review-store.mjs';\nglobalThis.__sidepanelReviews = reviews;"));
const assets=new Map([['/production.html','text/html; charset=utf-8'],['/prototype.html','text/html; charset=utf-8'],['/app.css','text/css'],['/app.js','text/javascript']]);
const server=http.createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname;if(path==='/other'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(`<!DOCTYPE html><title>${req.url.includes('reference=1')?'Northstar — Prototype demo':'Unrelated local page'}</title><h1>This page is outside the review.</h1>`);return;}if(!assets.has(path)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':assets.get(path),'Content-Security-Policy':"frame-ancestors 'none'"});res.end(await readFile(join(project,'demo',path.slice(1))));});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),results=[],errors=[];
const pass=message=>{results.push(message);console.log(`PASS ${message}`);};
async function until(check,label,timeout=15000){const start=Date.now();while(Date.now()-start<timeout){if(await check())return;await pause(100);}throw new Error(`Timed out: ${label}`);}
let context,worker,cdp,panel,production,source,extensionId;const pending=new Map();let sequence=0;
function nativeSend(sessionId,method,params={}){return new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(new Error(`Native view timeout: ${method}`));},8000);pending.set(id,{resolve,reject,timer});cdp.send('Target.sendMessageToTarget',{sessionId,message:JSON.stringify({id,method,params})}).catch(error=>{clearTimeout(timer);pending.delete(id);reject(error);});});}
async function nativeView(path){let target;await until(async()=>{target=(await cdp.send('Target.getTargets',{filter:[{exclude:false}]})).targetInfos.find(t=>t.type==='page'&&t.url===`chrome-extension://${extensionId}/${path}`);return target;},`native ${path}`);const{sessionId}=await cdp.send('Target.attachToTarget',{targetId:target.targetId,flatten:false});
  const send=(method,params)=>nativeSend(sessionId,method,params);
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.exception?.description||result.exceptionDetails.text);return result.result?.value;};
  await send('Runtime.enable');
  return{targetId:target.targetId,evaluate,
    visible:selector=>evaluate(`Boolean(document.querySelector(${JSON.stringify(selector)})?.checkVisibility())`),
    text:selector=>evaluate(`document.querySelector(${JSON.stringify(selector)})?.textContent||''`),
    value:selector=>evaluate(`document.querySelector(${JSON.stringify(selector)})?.value`),
    fill:async(selector,value)=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw new Error('Missing field '+${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`),
    click:async selector=>{const b=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e||!e.checkVisibility()||e.disabled)throw new Error('Unavailable control '+${JSON.stringify(selector)});e.scrollIntoView({block:'nearest'});const b=e.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2}})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...b});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...b});},
    screenshot:async name=>{const{data}=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(join(artifacts,`${name}.png`),Buffer.from(data,'base64'));}};
}
async function popupFor(page){await page.bringToFront();const targets=await cdp.send('Target.getTargets',{filter:[{type:'tab',exclude:false},{exclude:true}]});const target=targets.targetInfos.find(item=>item.url===page.url());assert(target);await cdp.send('Extensions.triggerAction',{id:extensionId,targetId:target.targetId});const popup=await nativeView('popup.html');await until(()=>popup.evaluate(`document.getElementById('popup')?.getAttribute('aria-busy')==='false'`),'popup initialized');return popup;}
const currentSession=()=>worker.evaluate(async()=> (await chrome.storage.session.get('comparison')).comparison);
const dimensions=page=>page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio}));
async function settledDimensions(page){let previous,stable=0,current;await until(async()=>{current=await dimensions(page);if(JSON.stringify(current)===JSON.stringify(previous))stable++;else stable=0;previous=current;return stable>=4;},'native viewport animation settles');return current;}
async function stopSession(){await panel.click('#panel-stop');await until(async()=>!await currentSession(),'session stopped');}
try{
  context=await chromium.launchPersistentContext(join(temporary,'profile'),{executablePath:chromium.executablePath(),headless:process.env.SIDEPANEL_HEADED!=='1',viewport:null,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`,'--enable-unsafe-extension-debugging','--window-size=1440,1000','--use-mock-keychain','--password-store=basic','--auto-select-tab-capture-source-by-title=Prototype demo']});
  worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker',{timeout:12000});extensionId=new URL(worker.url()).host;
  cdp=await context.browser().newBrowserCDPSession();
  cdp.on('Target.receivedMessageFromTarget',event=>{const message=JSON.parse(event.message),request=pending.get(message.id);if(request){clearTimeout(request.timer);pending.delete(message.id);message.error?request.reject(new Error(message.error.message)):request.resolve(message.result);}else if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.exception?.description||message.params.exceptionDetails.text);});
  source=context.pages()[0];await source.goto(`${origin}/prototype.html`);production=await context.newPage();await production.goto(`${origin}/production.html`);await production.bringToFront();
  const before=await dimensions(production);let popup=await popupFor(production);await popup.click('#open-side-panel');panel=await nativeView('sidepanel.html');await until(()=>panel.evaluate(`document.getElementById('popup')?.getAttribute('aria-busy')==='false'`),'panel initialized');
  await until(async()=>(await dimensions(production)).width<before.width-150,'native viewport shrinks');const docked=await settledDimensions(production);
  assert(!context.pages().some(page=>page.url().endsWith('/sidepanel.html')),'Native side panel must not be a normal browser tab');
  const panelDimensions=await panel.evaluate(`({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,fontSize:getComputedStyle(document.body).fontSize})`);assert(panelDimensions.scrollWidth<=panelDimensions.width+1);assert(parseFloat(panelDimensions.fontSize)>=15);
  assert.equal(await panel.visible('#feedback'),false,'Initial attachment must not leave a stale error');
  assert.equal(await panel.evaluate(`document.querySelectorAll('#mode-comparison,#mode-audit,#target-tab').length`),0,'Setup must not require mode or source/target selection');
  const controlSizes=await panel.evaluate(`['start-comparison','review-reports','ai-settings'].map(id=>{const b=document.getElementById(id).getBoundingClientRect();return{id,height:b.height}})`);for(const control of controlSizes)assert(control.height>=44,`${control.id} needs a44px target`);
  assert.match(await panel.text('#start-comparison'),/Start review/);await panel.screenshot('setup');await production.screenshot({path:join(artifacts,'page-docked.png')});pass('Native setup starts on the current page with one Start review action and no mode or tab-pair setup');
  await panel.click('#start-comparison');const overlay=production.locator('diffuse-live-overlay');await until(async()=>(await currentSession())?.status==='live','review starts on production');await until(()=>panel.visible('#dock-workspace'),'docked review controls');const initial=await currentSession(),reviewId=initial.reviewId;assert.equal(initial.sourceTabId==null,true);assert.equal(await overlay.locator('#layer').isVisible(),false);assert.equal(await overlay.locator('#divider').isVisible(),false);
  const readReview=()=>worker.evaluate(async()=>{const s=(await chrome.storage.session.get('comparison')).comparison;const r=await __sidepanelReviews.getReview(s.reviewId);return {id:r.id,count:r.count,comments:r.comments.map(c=>({id:c.id,fields:c.fields,selection:c.selection,viewport:c.context.production.viewport,evidence:{width:c.evidence.production.width,height:c.evidence.production.height,bytes:c.evidence.production.dataUrl.length,prototypeBytes:c.evidence.prototype?.dataUrl.length||0},hasVideo:!!c.evidence.video,videoBytes:c.evidence.video?.bytes||0}))};});
  const addRegion=async(text,category='ux-issue')=>{await until(()=>panel.visible('#panel-controls'),'review controls');await panel.click('#panel-area');await production.mouse.move(300,240);await production.mouse.down();await production.mouse.move(580,365,{steps:8});await production.mouse.up();await until(()=>panel.visible('#panel-comment-form'),'docked region composer');await panel.fill('#panel-field-comment',text);await panel.fill('#panel-field-category',category);await panel.screenshot('comment-draft');await panel.click('#panel-save-comment');};
  await addRegion('This page can be reviewed before choosing a reference.');await until(async()=>(await currentSession()).commentCount===1,'first review comment saved');const first=(await readReview()).comments[0];assert.equal(first.evidence.prototypeBytes,0);assert.equal(first.selection.rect.viewport.width,280);assert.equal(first.selection.rect.viewport.height,125);assert.equal(first.viewport.width,docked.width);assert.equal(first.evidence.width,Math.round(first.viewport.width*first.viewport.dpr));assert.equal(first.evidence.height,Math.round(first.viewport.height*first.viewport.dpr));pass('A screenshot comment saves on the current page before Diff is used, with native drawer pixels excluded');
  await source.bringToFront();await settledDimensions(source);await production.bringToFront();const sourceId=await worker.evaluate(async url=>(await chrome.tabs.query({url}))[0].id,source.url());
  const grantError=await worker.evaluate(async tabId=>{try{await chrome.tabCapture.getMediaStreamId({targetTabId:tabId});return null;}catch(error){return error.message;}},sourceId);assert.match(grantError,/activeTab|not been invoked/i);
  const openDiff=async()=>{await until(()=>panel.evaluate(`Boolean(document.getElementById('panel-diff')?.checkVisibility()&&!document.getElementById('panel-diff').disabled)`),'Diff control ready after tab change');await panel.click('#panel-diff');let picker;await until(async()=>{picker=context.pages().find(page=>page.url().startsWith(`chrome-extension://${extensionId}/diff.html`));return picker;},'Diff reference picker');await picker.waitForLoadState();await until(()=>picker.locator('#reference-tab').isEnabled(),'reference dropdown');return picker;};
  let picker=await openDiff();await picker.locator('#reference-tab').selectOption(String(sourceId));await picker.screenshot({path:join(artifacts,'reference-picker.png')});await picker.locator('#connect-reference').click();await until(async()=>{if(!picker.isClosed()){const feedback=await picker.locator('#diff-feedback').textContent();if(feedback)throw new Error('Reference picker: '+feedback);}const s=await currentSession();return s?.sourceTabId===sourceId&&s.status==='live';},'reference attaches through native sharing consent',25000);await until(()=>overlay.locator('#reference').evaluate(video=>video.readyState>=2&&video.videoWidth>0).catch(()=>false),'verified reference live stream',25000);
  assert.equal((await currentSession()).reviewId,reviewId);assert.equal((await currentSession()).commentCount,1);assert.deepEqual((await readReview()).comments[0],first);assert.equal(await overlay.locator('#layer').isVisible(),true);await until(()=>panel.visible('#panel-hide'),'reference controls');await panel.click('#panel-hide');await until(()=>overlay.locator('#layer').isVisible().then(visible=>!visible),'existing hide toggle hides Diff');await until(()=>panel.evaluate(`document.getElementById('panel-hide').getAttribute('aria-pressed')==='true'`),'native toggle reflects hidden state');await panel.click('#panel-hide');await until(()=>overlay.locator('#layer').isVisible(),'existing hide toggle shows Diff');
  const sourceSize=await dimensions(source),targetSize=await dimensions(production),stream=await overlay.locator('#reference').evaluate(video=>({width:video.videoWidth,height:video.videoHeight}));assert.equal(sourceSize.width,targetSize.width);assert(Math.abs(stream.width-sourceSize.width*sourceSize.dpr)<=2);await panel.screenshot('comparison');pass('Diff attaches a verified live reference without invoking its toolbar and preserves the review and earlier evidence');
  const streamedPixel=()=>overlay.locator('#reference').evaluate(video=>{const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;const ctx=canvas.getContext('2d');ctx.drawImage(video,0,0);return [...ctx.getImageData(5,5,1,1).data];});
  await source.evaluate(()=>{const marker=document.createElement('div');marker.id='diffuse-native-stream-marker';marker.style.cssText='position:fixed;left:0;top:0;width:32px;height:32px;background:rgb(255,0,0);z-index:2147483647';document.documentElement.append(marker);});await until(async()=>{const pixel=await streamedPixel();return pixel[0]>200&&pixel[2]<60;},'red live background reference frame');await source.evaluate(()=>document.getElementById('diffuse-native-stream-marker').style.background='rgb(0,0,255)');await until(async()=>{const pixel=await streamedPixel();return pixel[2]>200&&pixel[0]<60;},'blue live background reference frame');await source.evaluate(()=>document.getElementById('diffuse-native-stream-marker').remove());pass('Native reference capture streams changing background-tab pixels into the production overlay');
  await addRegion('Comparison evidence keeps both captured pages.','design-mismatch');await until(async()=>(await currentSession()).commentCount===2,'paired comment saved');const paired=(await readReview()).comments[1];assert(paired.evidence.prototypeBytes>1000);
  const other=await context.newPage();await other.goto(`${origin}/other`);await until(()=>panel.visible('#panel-away'),'unrelated tab notice');assert.equal(await panel.visible('#panel-live'),false);assert.equal((await currentSession()).targetTabId,initial.targetTabId);await production.bringToFront();await until(()=>panel.visible('#panel-live'),'review controls return on production');const otherId=await worker.evaluate(async url=>(await chrome.tabs.query({url}))[0].id,other.url());pass('Switching tabs preserves the review target and guards unrelated pages');
  picker=await openDiff();await picker.locator('#reference-tab').selectOption(String(otherId));await picker.locator('#connect-reference').click();await until(()=>picker.locator('#feedback,[role="alert"]').allTextContents().then(items=>/match|selected|reference|share/i.test(items.join(' '))),'wrong shared tab is rejected',25000);assert.equal((await currentSession()).sourceTabId,sourceId);assert.equal((await currentSession()).reviewId,reviewId);assert.equal((await currentSession()).status,'live');assert.deepEqual((await readReview()).comments[1],paired);await picker.screenshot({path:join(artifacts,'wrong-reference.png')});await picker.close();await production.bringToFront();pass('Sharing a different tab than the dropdown selection rejects the candidate and retains the previous reference');
  await source.evaluate(()=>document.title='Original reference retained');await other.goto(`${origin}/other?reference=1`);await until(async()=>{const tabs=await worker.evaluate(()=>chrome.tabs.query({}));return tabs.some(tab=>tab.id===otherId&&tab.title==='Northstar — Prototype demo')&&tabs.some(tab=>tab.id===sourceId&&tab.title==='Original reference retained');},'Chrome tab titles settle before share chooser');await other.bringToFront();await settledDimensions(other);await production.bringToFront();picker=await openDiff();await picker.locator('#reference-tab').selectOption(String(otherId));await picker.locator('#connect-reference').click();await until(async()=>{const s=await currentSession();return s?.sourceTabId===otherId&&s.status==='live';},'replacement reference commits',25000);assert.equal((await currentSession()).reviewId,reviewId);assert.deepEqual((await readReview()).comments[1],paired);pass('Changing the reference preserves saved paired screenshots and the same review');
  picker=await openDiff();await picker.locator('#remove-reference').click();await until(async()=>(await currentSession()).sourceTabId==null,'Diff reference removed');assert.equal((await currentSession()).reviewId,reviewId);assert.equal((await currentSession()).commentCount,2);assert.deepEqual((await readReview()).comments[1],paired);await until(()=>overlay.locator('#layer').isVisible().then(visible=>!visible),'reference overlay removed');await production.bringToFront();pass('Removing Diff returns to page review without discarding comments or reference evidence');
  await until(()=>panel.visible('#panel-controls'),'review controls after reference removal');await until(async()=>await panel.evaluate('session?.id')===(await currentSession()).id&&!await panel.visible('#panel-comparison-controls'),'drawer reflects reference removal');await panel.click('#panel-record');await until(async()=>Boolean((await currentSession()).recording),'recording starts from drawer');await pause(1200);await panel.click('#panel-record');await until(()=>panel.visible('#panel-comment-form'),'recording composer in drawer');await until(()=>panel.evaluate(`document.getElementById('panel-recording-preview').readyState>=1`),'native drawer recording preview decodes');await panel.fill('#panel-field-comment','The drawer can attach a short recording of the page.');await panel.screenshot('recording-draft');await panel.click('#panel-save-comment');await until(async()=>(await currentSession()).commentCount===3,'recording comment saved');const recorded=(await readReview()).comments[2];assert.equal(recorded.hasVideo,true);assert(recorded.videoBytes>1000);pass('Native drawer records, previews and saves a real page clip after Diff is removed');
  await until(()=>panel.visible('#panel-controls'),'controls after recording');await panel.click('#panel-area');await production.mouse.move(300,260);await production.mouse.down();await production.mouse.move(540,360,{steps:6});await production.mouse.up();await until(()=>panel.visible('#panel-comment-form'),'unfinished review composer');await panel.fill('#panel-field-comment','Review draft remains safe when the drawer closes.');await until(()=>overlay.locator('#comment-actual').inputValue().then(value=>value==='Review draft remains safe when the drawer closes.'),'comment fields reach on-page controller');
  const active=await currentSession();await worker.evaluate(async()=>{const tab=await chrome.tabs.get((await chrome.storage.session.get('comparison')).comparison.targetTabId);await chrome.sidePanel.close({windowId:tab.windowId});});await until(async()=>(await dimensions(production)).width===before.width,'page restores width after native close');await until(()=>overlay.locator('#comment-form').isVisible(),'floating composer returns');assert.equal(await overlay.locator('#comment-actual').inputValue(),'Review draft remains safe when the drawer closes.');assert.equal((await currentSession()).id,active.id);assert.equal(await overlay.locator('#toolbar').isVisible(),false);await production.screenshot({path:join(artifacts,'drawer-closed-draft.png')});pass('Closing the drawer restores page width and preserves an unfinished comment without a floating toolbar');
  assert.deepEqual(errors,[],'Native extension views reported an uncaught exception');await writeFile(join(artifacts,'results.json'),JSON.stringify({chromeVersion:context.browser().version(),before,docked,panelDimensions,sourceSize,targetSize,stream,results},null,2));
}catch(error){for(const page of context?.pages()||[])if(page.url().includes('/diff.html')){console.log('DIFF DIAGNOSTIC',await page.locator('body').innerText().catch(()=>''));await page.screenshot({path:join(artifacts,'failure-picker.png')}).catch(()=>{});}console.log('SESSION DIAGNOSTIC',await currentSession().catch(()=>null));if(panel)await panel.screenshot('failure-panel').catch(()=>{});await production?.screenshot({path:join(artifacts,'failure-page.png')}).catch(()=>{});throw error;}
finally{for(const request of pending.values()){clearTimeout(request.timer);request.reject(new Error('Test ended'));}pending.clear();await context?.close();await new Promise(resolve=>server.close(resolve));await rm(temporary,{recursive:true,force:true});}
