(() => {
  const paths = {grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',layers:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 5v2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M16 3v4M8 3v4M3 11h18"/>',check:'<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 6-3 6-3 9h18c0-3-3-3-3-9m-8 12h4"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 8.5a2.5 2.5 0 0 1 5 0c0 2-2.5 2-2.5 4m0 3v1"/>'};
  const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.grid}</svg>`;
  const brand = '<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><rect width="32" height="32" rx="10" fill="#6941C6"/><path d="M10 23V9h14v5H15v3h7v5h-7v1" fill="#fff"/><circle cx="24" cy="8" r="4" fill="#EF785C"/></svg>';
  const avatars = '<div class="avatar-stack"><span class="avatar">AM</span><span class="avatar">JL</span><span class="avatar">SK</span></div>';
  const project = (name, description, art, status, due, coral = '') => `<article class="project" data-component="ProjectCard"><div class="art art-${art}" aria-hidden="true">${art==='helio'?'<div class="orb"></div>':art==='atelier'?'<div class="arch"></div><div class="tile"></div>':'<div class="disc"></div>'}</div><div class="project-info"><div class="project-topline"><h3>${name}</h3><span class="status-pill ${coral}">${status}</span></div><p class="project-description">${description}</p><div class="project-footer">${avatars}<span>${due}</span></div></div></article>`;
  document.querySelector('#showcase-app').innerHTML = `
    <aside class="side" aria-label="Studio navigation"><a class="brand" href="#overview">${brand}forma</a><div class="workspace"><span class="badge">S</span>Studio workspace<span style="margin-left:auto;font-size:10px">⌄</span></div><p class="section-label">Workspace</p><nav class="nav"><a href="#overview" class="selected" aria-current="page">${icon('grid')}Overview</a><a href="#projects">${icon('layers')}Projects<span class="count">8</span></a><button data-toast="All team members are up to date.">${icon('people')}Team</button><a href="#schedule">${icon('calendar')}Schedule</a></nav><div class="side-bottom"><nav class="nav"><button data-toast="Fictional demo. Try New project to explore an interactive state.">${icon('help')}Help & shortcuts</button></nav><div class="member"><span class="avatar">AM</span><div><strong>Alex Morgan</strong><span>Studio lead</span></div></div><div class="demo-label">Fictional ${document.body.dataset.version} demo</div></div></aside>
    <div class="shell"><header class="top"><div class="crumb">Workspace<span>/</span><strong>Overview</strong></div><div class="top-right"><span class="search">${icon('search')}Search your studio<kbd>⌘ K</kbd></span><button class="icon-button" aria-label="Notifications" data-toast="You're all caught up.">${icon('bell')}</button><span class="avatar">AM</span></div></header><main class="main" id="overview"><p class="eyebrow"><span class="dot"></span>Wednesday, September 30</p><div class="heading" data-component="PageHeader"><div><h1>A little space. A lot of possibility.</h1><p class="subtitle">Your studio's work, people, and next bright ideas — together.</p></div><button id="showcase-open-project" class="primary" data-component="CreateProjectButton">${icon('plus')}New project</button></div>
    <section class="metrics" aria-label="Studio progress" data-component="StudioMetrics"><article class="metric"><div class="metric-name">Active projects${icon('layers')}</div><div class="metric-value">8 <small>/ 12</small></div><div class="metric-note"><strong>2 new projects</strong> this month</div></article><article class="metric"><div class="metric-name">Ready for review${icon('check')}</div><div class="metric-value">24</div><div class="metric-note"><strong>6 updates</strong> since yesterday</div></article><article class="metric"><div class="metric-name">Next studio milestone${icon('calendar')}</div><div class="metric-value">3 <small>days</small></div><div class="metric-note">Helio identity · Final presentation</div></article></section>
    <section id="projects" aria-labelledby="projects-title"><div class="section-heading"><h2 id="projects-title">Work taking shape</h2><div class="tabs" role="tablist" aria-label="Project views"><button role="tab" aria-selected="true">All projects</button><button role="tab" aria-selected="false" tabindex="-1">My projects</button></div></div><div class="cards">${project('Helio identity','A warmer kind of energy.','helio','In review','Oct 03','coral')}${project('Atelier website','A new home for thoughtful work.','atelier','In progress','Oct 08')}${project('Orbit design system','Made to move with your team.','orbit','In progress','Oct 12')}</div></section>
    <div class="lower"><section class="panel" aria-label="Recent activity"><h2>Around the studio</h2><article class="activity"><span class="avatar">JL</span><div><p><strong>Jamie Lee</strong> shared a new identity direction</p><small>Helio identity · 12 minutes ago</small></div></article><article class="activity"><span class="avatar" style="background:#e8def7;color:#654781">SK</span><div><p><strong>Sam Kim</strong> added feedback to the component library</p><small>Orbit design system · 35 minutes ago</small></div></article><article class="activity"><span class="avatar">AM</span><div><p><strong>Alex Morgan</strong> moved homepage explorations to review</p><small>Atelier website · 1 hour ago</small></div></article></section><section class="panel" id="schedule"><h2>Coming into focus</h2><div class="schedule"><div class="date">OCT<strong>03</strong></div><div><h3>Helio · Final presentation</h3><p>10:00–11:00 · Studio room</p></div></div><div class="schedule"><div class="date">OCT<strong>06</strong></div><div><h3>Weekly design review</h3><p>14:00–15:00 · All hands</p></div></div></section></div></main></div>
    <dialog class="drawer" id="showcase-drawer" aria-labelledby="drawer-title"><header class="drawer-header"><h2 id="drawer-title">Start something good.</h2><button class="icon-button" id="showcase-close-drawer" aria-label="Close project form">${icon('close')}</button></header><form id="showcase-project-form" class="drawer-body" data-component="CreateProjectForm"><p>A name, a little context, and room to explore.</p><label class="field">Project name<input id="showcase-project-name" required maxlength="80" placeholder="Your next bright idea" autocomplete="off"></label><label class="field">A little context <small>Optional</small><textarea id="showcase-project-description" placeholder="What are we making together?" maxlength="300"></textarea></label><label class="field">Project type<select id="showcase-project-type"><option>Brand identity</option><option>Digital experience</option><option>Design system</option></select></label><div class="drawer-actions"><button class="secondary" type="button" id="showcase-cancel-project">Cancel</button><button class="primary" type="submit">Create project${icon('arrow')}</button></div></form></dialog><div class="toast" role="status" aria-live="polite"></div>`;
  let timer;
  const toast = text => { clearTimeout(timer); document.querySelector('.toast').textContent=text; timer=setTimeout(()=>{document.querySelector('.toast').textContent='';},3000); };
  document.querySelectorAll('[data-toast]').forEach(button=>button.addEventListener('click',()=>toast(button.dataset.toast)));
  const drawer=document.querySelector('#showcase-drawer');
  document.querySelector('#showcase-open-project').addEventListener('click',()=>drawer.showModal());
  for(const id of ['showcase-close-drawer','showcase-cancel-project'])document.getElementById(id).addEventListener('click',()=>drawer.close());
  document.querySelector('#showcase-project-form').addEventListener('submit',event=>{event.preventDefault();const name=document.querySelector('#showcase-project-name').value.trim();if(!name)return;drawer.close();toast(`${name} is ready for your first idea.`);});
  const tabs=[...document.querySelectorAll('[role=tab]')];
  const selectTab=button=>{tabs.forEach(item=>{item.setAttribute('aria-selected',String(item===button));item.tabIndex=item===button?0:-1;});toast(button.textContent==='My projects'?'Showing projects you contribute to.':'Showing all studio projects.');};
  tabs.forEach((button,index)=>{button.addEventListener('click',()=>selectTab(button));button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const next=tabs[(index+1)%tabs.length];selectTab(next);next.focus();});});
})();
